const pizzaData = [
  {
    data: `{"1":2,"2":"What It's Called: Xanadu\\n\\nWhat's On It: All-organic mac sauce, blanched broccoli, and Cajun jackfruit \\n\\nWhat They Say About It: \\"Much beauty is in the swamp, if you only look\\" -Swamp Thing\\n\\nPreconceived notions have not caught up to the reality of amazing vegan pizza...It's easy to say this Cheesy-Broc Cajun-Jackfruit pizza will blow your mind... but that doesn't do it justice...Walk Amongst the Beauty with Us\\n\\nWhere and When to Get It: Secret Pizza Society , Monday-Thursday 12-9 pm, Friday-Saturday 1-10 pm / 7201 NE Glisan St\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegan\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? No\\nMore Details: 2 full Pie limit per customer"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Highway Raabery\\n\\nWhat's On It: Broccoli rabe, confit garlic, mozzarella, pecorino, garlic oil\\n\\nWhat They Say About It: This week will be our first anniversary of being on Mississippi, and what better way to celebrate a trip around the sun than Pizza Week!  We went with a classic take on a broccoli rabe, confit garlic pie, finished with garlic oil and pecorino.  We are a farm-to-table Italian restaurant that focuses on local ingredients, inventive cocktails, and fine, but approachable wine. Come for the pizza, stay for all of the wonderful fun to be had on Mississippi!\\n\\nWhere and When to Get It: Tartuca, 3951 N Mississippi Ave / Monday-Thursday 4-9 pm, Friday-Saturday 11:30 am-2:30 pm (we are not offering it on Friday or Saturday night dinner service, it's just too busy!), Sunday 11:30 am-2:30 pm, 4-9 pm\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? Whole Pie\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? Yes1 pie per party\\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: I love you elote\\n\\nWhat's On It: Street corn pizza is a delicious fusion of Mexican street food and Italian cuisine. The pizza features a crispy crust topped with a flavorful combination of seasoned corn and a tantalizing Tajin, chipotle, and lime sauce. The corn is carefully seasoned with a blend of spices, including garlic, pepper, and salt and topped with cotija cheese. \\nTo complement the sweet and spicy flavors of the corn, the pizza is topped with tangy pickled onions and fresh cilantro. The pickled onions provide a pleasant crunch and a hint of acidity that perfectly balances the richness of the cheese and the sweetness of the corn.\\n\\nWhat They Say About It: \\nDo you love corn? Of course you do, It's Corn! Get ready to be wowed by our corn-forward slice seasoned with warm elote style spices and topped with all the hits - creamy cotija cheese, crisp pickled onion, cilantro, and a Tajin-chipotle lime sauce. We can't imagine a more beautiful thing.\\n\\nWhere and When to Get It: Baby Doll Pizza, 2835 SE Stark St / 11 am-10 pm daily\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? By the Slice\\nAllow Minors? Yes\\nAllow Takeout? No\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? Yes800 slice limit per day\\nMore Details: Not available to-go or delivery. Limit 2 slice per person. "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Cheeked Up\\n\\nWhat's On It: Braised beef cheek Bolognese, basil aioli, Parmigiano Reggiano \\n\\nWhat They Say About It: Beef cheeks are one of my favorite things to braise, and a rich Bolognese base is perfect for them. The addition of an old-school basil aioli and shaved Parm brings this hearty slice to the next level. I haven't put a Bolognese on a menu in a while, and was really happy with how well it works as a pizza topping. There are a handful of traditional pasta sauces that make great toppings, and this is one of them! \\n\\nWhere and When to Get It: Meta Pizza, Tuesday-Sunday 3-9 pm / 3541 SE Milwaukie Ave\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? Yes\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: Meta Pizza is on DoorDash, UberEats and Grub Hub"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Birria Pie\\n\\nWhat's On It: Jackfruit birria, mozzarella, cheddar, fresh onion, and cilantro.  Served with a side of consome.\\n\\nWhat They Say About It: Everyone loves birria, so why not put it on a pizza? Our naturally leavened sourdough is fluffy in the middle and crunchy on the bottom - and our slices are deceptively filling.\\n\\nWhere and When to Get It: Boxcar Pizza , 11:30 am-9 pm daily  / 2701 NE Sandy Blvd\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegan\\n\\nBy the Slice or Whole Pie? By the Slice\\n\\nAllow Minors? Yes\\n\\nAllow Takeout? Yes\\n\\nAllow Delivery? Yes\\n\\nPurchase Limit per Customer? No\\n\\nDaily Availability Limit? No - \\n\\nMore Details: Doordash (can be ordered via our website boxcarpizzapdx.com)"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Baked Potato with Smoked Pork Belly Pie\\n\\nWhat's On It: Potato, cheddar and mozzarella cheeses, smoked pork belly, green onion, and crema \\n\\nWhat They Say About It: This was the inspiration of our GM at Cascade and his love of baked potatoes (and pizza).  We kept the house-smoked meat theme here and elevated our baked potato pie with pork belly!\\n\\nWhere and When to Get It: Von Ebert Brewing Pizzeria & Taproom, 11 am-9 pm daily / 10111 NE Cascades Pwky\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: The Bite of the Valkyries\\n\\nWhat's On It: Beyond Swedish meatballs, Parmesan cream, lingonberry sauce, and fresh dill.\\n\\nWhat They Say About It: Just like IKEA, except we're assembling it for you, and it tastes much better. A rich vegetarian pie inspired by Scandinavian cuisine, it will send you straight to Valhalla (which is what the Old Norse called Flavortown).\\n\\nWhere and When to Get It: Paladin Pie, Tuesday-Thursday 4-9 pm, Friday-Sunday 12-10 pm / 2231 NE Alberta St\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? I Need To Explain\\nDaily Availability Limit? No - \\nMore Details: Two slices per person, no limit on whole pies. Slices only available for walk-up."}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: La 'Zagna\\n\\nWhat's On It: Mornay Sauce base with mozzarella, meaty Bolognese, and ricotta, topped with fresh basil and shredded Parmesan\\n\\nWhat They Say About It: Spring's the last chance to desecrate your body with too much cheese before you get working on your summer abs. Our La 'Zagna slice has Mornay sauce, meaty Bolognese, basil, and, of course, mozzarella! Ricotta! Parm! Hurry in and wolf down a slice before someone says "detox" and ruins your day.\\n\\n\\nWhere and When to Get It: Old Town Brewing, Monday-Thursday 4-9 pm, Friday 3-9 pm, Saturday 12-9 pm, Sunday 4-9 pm / 5201 NE Martin Luther King Jr Blvd\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? I Need To Explain\\nDaily Availability Limit? No\\nMore Details: 2 Slices per person, per transaction. "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Ace 'Rose Pie\\n\\nWhat's On It: 100% tomato sauce, Asiago cheese, imported Gorgonzola, sweet fig preserve, prosciutto, Romano cheese, house-made balsamic glaze \\n\\nWhat They Say About It: We are always looking to satisfy customers with our fresh ideas and delicious dishes. Our recipes has been around many years dating back to our family restaurants in Italy, Greece, and Bulgaria. \\n\\nWhere and When to Get It: Love Verona Pizza/Pasta & Bottega, 11 am-10 pm daily / 540 SW College St\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat, Vegetarian\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? Yes\\nPurchase Limit per Customer? No\\nDaily Availability Limit? NoUnlimited \\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: The Famous Cold Cheese Pizza\\n\\nWhat's On It: Cheese pizza with red sauce, shredded mozz, and fresh mozz. After it cooks, it's finished with cold shredded mozz so you can enjoy!\\n\\nWhat They Say About It: This is a pizza trend out of the Midwest. Finishing the pizza with cold, shredded mozz allows you to enjoy the pizza without burning your mouth! \\n\\nWhere and When to Get It: Red Sauce Pizza, Monday-Thursday 4-8 pm, Friday-Saturday 4-8:30 pm, Sunday 4-8 pm / 4641 NE Fremont St\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? Whole Pie\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? Yes\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: DoorDash is our delivery app. We also have a mandatory 20% gratuity."}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Is it Shawarma in here? (or is it just me?)\\n\\nWhat's On It: Herby garlic sauce, mozzarella, spiced yogurt-marinated chicken thighs, pickles, and house hot sauce.\\n\\nWhat They Say About It: \\"You got pizza in my Shawarma!\\"  \\"You got Shawarma on my pizza!\\"  Two great tastes come together to make a savory, garlicky, spicy slice.\\n\\nWhere and When to Get It: East Glisan Pizza Lounge, 8001 NE Glisan St. / Monday-Wednesday 5-9 pm, Thursday-Saturday 5-11 pm, Sunday 5-9 pm\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? I Need To Explain\\nDaily Availability Limit? No\\nMore Details: 2 slices per person"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: The Sammy Special\\n\\nWhat's On It: Spinach, bacon, mushrooms, Roma tomato, and garlic\\n\\nWhat They Say About It: For our first time at Pizza Week, we decided to go with a crowd-pleaser: The Sammy Special! Named after the girl who created it, this pie is designed to be a well-balanced meal, if not a bit indulgent ;) Ask for a side of the Good Sauce if you're feelin' fancy!\\n\\nWhere and When to Get It: The Blind Onion, Monday-Thursday 11 am-10 pm, Friday-Saturday 11 am-11 pm, Sunday 11 am-10 pm / 6031 SE Belmont St\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Nonna Gracie's Lasagna \\n\\nWhat's On It: Savory tomato and vegetable sauce, topped with layer upon layer of spinach, ricotta, and mozzarella cheese.\\n\\nWhat They Say About It: Just like lasagna, pizza is good for you. Our chewy and charred crust is topped with layers of cheese and vegetables. It's delicious and nutritious. \\n\\nWhere and When to Get It: Gladstone Street Pizza, 3813 SE Gladstone St / Monday-Wednesday 4-10 pm, Thursday-Saturday 4-11 pm, Sunday 4-9 pm\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? Both\\nAllow Minors? I Need To Explain\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? I Need To Explain\\nDaily Availability Limit? YesOur kitchen size limits our production capacity to about 60-70 pies a day. \\nMore Details: No minors in the lounge after 9 pm, all ages seating on the heated patio until closing.\\nLimit 2 slices per person, 2 whole pies per order.\\n"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Max's Chicken Tinga Pizza\\n\\nWhat's On It: Chipotle lime cream sauce, mozzarella, tinga chicken, pickled onion, queso fresco, cilantro\\n\\nWhat They Say About It: Our Chicken Tinga Pizza was created by our beloved employee, Max Doyle. When Max was asked to come up with a pizza special, he was inspired to recreate one of his favorite foods, the street taco, in pizza form. We might be biased, but we think Max nailed taco meets pizza with his Chicken Tinga Pizza! \\n\\nWhere and When to Get It: Oakshire Beer Hall , Monday-Sunday, 12-9:30 pm / 5013 NE 42nd Ave\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Whole Pie\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? No\\nDaily Availability Limit? Yes20\\nMore Details: This is not an explain, but a question. This is our first time participating in pizza week, and we were curious if we are terribly under what the limit of number of pies/day should be. How many do other businesses do per day? Thanks for your help and guidance here. "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Smoked Pork Belly Enchilada Pie \\n\\nWhat's On It: \\n\\nWhat They Say About It: We wanted to combine one of our house-smoked meats with one of our favorite foods, burritos.  After the meeting of the minds, here is what we came up with!\\n\\nWhere and When to Get It: Von Ebert Brewing Pizzeria & Taproom, 1800 NW Cedar Falls Dr / Monday-Thursday 11:30 am-9 pm, Friday-Saturday 11:30 am-10 pm, Sunday 11:30 am-9 pm\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Kalua-Inspired Shredded Pork Hawaiian \\n\\nWhat's On It: Tomato sauce, smoked mozzarella, Kalua-inspired shredded pork, sweet onions, fresh pineapple, green onions, and house-made huli-huli drizzle.\\n\\nWhat They Say About It: A little taste of Island-inspired sunshine during the rainy Pacific Northwestern spring. This is not the Hawaiian pizza you grew up with!\\n\\nWhere and When to Get It: Sunny's Pizza, Monday-Thursday 4-8 pm, Friday-Saturday 12-9 pm, Sunday 12-8 pm / 7738 SE 13th Ave\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? By the Slice\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? Yes\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Fowl Play\\n\\nWhat's On It: Fried chicken, bacon, pickles, red cabbage, spicy maple dressing, and red pepper flakes\\n\\nWhat They Say About It: Everyone was shocked when Old McDonald passed away under suspicious circumstances. Astonishingly, he posthumously gifted us this recipe—now we've been working around the cluck! With fried chicken, bacon, pickles, red cabbage, spicy maple dressing, and red pepper flakes, there's one thing we can say for sure — it tastes like chicken.\\n\\nWhere and When to Get It: SFNY Hawthorne, Monday-Thursday 11 am-11 pm, Friday-Saturday 11 am-midnight, Sunday 11 am-11 pm / 3701 SE Hawthorne Blvd\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? No\\nMore Details: Max 2 slices per person. 14\\" whole pies available to order on our website, or by phone (phone lines may be busy)"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Where Have Reuben All My Life \\n\\nWhat's On It: A slightly sweet spicy mustard sauce with caraway seeds topped with mozzarella cheese, corned beef, sauerkraut, and sliced Swiss, topped with a Russian dressing. \\n\\nWhat They Say About It: Our take on a classic, we've finally found what's been missing! It's this tasty pie! \\n\\nWhere and When to Get It: Signal Station Pizza, Monday-Thursday 11:30 am-8:30 pm, Friday-Saturday 11:30 am-9 pm, Sunday 12-8 pm / 8302 N Lombard\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? By the Slice, Whole Pie, Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? Yes2 slices per person \\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Thai Hard 2\\n\\nWhat's On It: Curried peanut sauce, chicken, roasted red peppers, red onion, mozzarella, cashews, scallion\\n\\nWhat They Say About It: Killingsworth is BACK to Thai Harder with another fusion this year! Creamy house-made curried peanut sauce base is the star of the show on this pie, bub!\\n\\nWhere and When to Get It: Atlas Pizza, 710 N Killingsworth / Monday-Thursday 11:30 am-9 pm, Friday-Saturday 11:30 am-10 pm, Sunday 11:30 am-9 pm\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? By the Slice\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? No\\nMore Details: 3 pizza week slices per customer per day!"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Tajin Clasico\\n\\nWhat's On It: Olive oil base, signature cheese blend, pineapple, red onion, fresh mozzarella, and green onion with a dusting of Tajin\\n\\nWhat They Say About It: The Tajin Clasico has a bright citrusy taste with a subtle chile flavor over pineapple and fresh mozzarella! A little bit savory, a little bit sweet with just a touch of heat.\\n\\nWhere and When to Get It: Sizzle Pie, Monday-Wednesday 11 am-10 pm, Thursday-Saturday 11 am-midnight, Sunday 11 am-10 pm / 949 SW Oak St\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? Yes\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: The Swine\\n\\nWhat's On It: Slab bacon, shredded pork, caramelized onions, and BBQ sauce with house-made marinara and shredded mozz\\n\\nWhat They Say About It: Our inspiration for this pie is mostly our Swine Whiskey Bar and how it would pair well with something peated.\\n\\nWhere and When to Get It: Taylor Street Tavern, Tuesday-Saturday 5-10 pm / 808 SW Taylor St\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Whole Pie\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Ballz Deep\\n\\nWhat's On It: Classic meatball pie\\n\\nWhat They Say About It: We bang your mouth hard!\\n\\nWhere and When to Get It: Dante's Pizza Slut, 11 am-2:30 am daily / 1 SW 3rd Ave\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Both\\nAllow Minors? I Need To Explain\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: MInors will be served at the pizza window on 3rd"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Mexican Street Corn\\n\\nWhat's On It: Roasted garlic crema, grilled sweet corn, pickled red onions, cilantro, and mozzarella, finished with cotija and ground ancho chili powder.\\n\\nWhat They Say About It: The Mexican Street Corn pizza features our newly famous crispy crust, topped with roasted garlic crema, melted cotija cheese, grilled corn, and pickled red onions, finished with a cilantro and ancho chili powder. This pizza is bursting with bold and tangy flavors and is a true feel-good recipe!\\n\\nWhere and When to Get It: Wild Child Pizza, 2032 NE Alberta St and 2309 NW Kearney St / Monday-Thursday 3-9 pm, Friday-Saturday 3-10 pm, Sunday 3-9 pm\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Rudy's Princess Peach Pizza\\n\\nWhat's On It: Rudy's housemade red sauce topped with spicy vegan sausage, grilled onion, chopped peaches, and a three cheese blend (can be made with meat, vegetarian, or vegan)\\n\\nWhat They Say About It: Inspired by the upcoming \\"Super Mario Bros. Movie\\" out this spring, we created Rudy's Princess Peach Pizza to be a delicious pizza to take you back to your childhood days!\\n\\nWhere and When to Get It: Rudy's Pizza, Monday-Thursday 12-11 pm, Friday-Saturday 12 pm-12 am, Sunday 12-11 pm / 2443 SE Powell Blvd\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegan\\nBy the Slice or Whole Pie? Whole Pie\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? Yes\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: DoorDash, Uber Eats and GrubHub. Also, our whole pizza can be made traditional or vegan. We are not offering this pizza by the slice."}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Nacho Libre\\n\\nWhat's On It: Nacho cheese base, mozzarella, diced jalapeño, tomato, olive, black beans, scallions \\n\\nWhat They Say About It: Our Foster shop is back at the Ballpark this year with an ode to another stadium staple: NACHOS! A \\"stadium cheese\\" base (aka the gooiest, most decadent nacho cheese on the planet) makes this pie a real home run. Pair with some Newks Hot Sauce, available in all our shops - and you're outta here, bub!\\n\\nWhere and When to Get It: Atlas Pizza, 6529 SE Foster Rd / 4-10 pm daily\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? By the Slice\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? No\\nMore Details: 3 slices of pizza week pie per customer per day!"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Kale Pizza\\n\\nWhat's On It: Green garlic cream, asiago fresco, guanciale, and Meyer lemon\\n\\nWhat They Say About It: We at Cicoria always try to be as seasonal as possible, because seasonal means tasty! Kale rabe is only available in the late winter and early spring, so now is prime time! Pair that with the early green garlic, some super salty-sweet asiago fresco and crispy guanciale, and we have a flavor explosion. Our super thin-crust, tavern-style, party-cut pizza allows for each piece to be a little different and a lot of fun!\\n\\nWhere and When to Get It: Cicoria , Wednesday-Thursday 5-9 pm, Friday-Saturday 5-10 pm, Sunday 5-9 pm / 3377 SE Division St\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Whole Pie\\nAllow Minors? Yes\\nAllow Takeout? I Need To Explain\\nAllow Delivery? No\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: We will allow take-out however it is limited due to constraints of the business of dine-in."}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Mushroom: Impossible — Ricotta Protocol\\n\\nWhat's On It: Shiitake mushrooms, asparagus, Castelvetrano olives, ricotta, and green goddess dressing\\n\\nWhat They Say About It: Welcome back, Pizza Week. In your absence, SFNY has learnt that there are many covert ways to a delicious pie. This pizza ~should you choose to accept it~ will include shiitake mushrooms, asparagus, Castelvetrano olives, ricotta, and green goddess dressing. As always, we won't disavow you or any members of your team, but be warned: Your taste buds may self-destruct.\\n\\nWhere and When to Get It: SFNY Belmont, Monday-Thursday 11 am-midnight, Friday-Saturday 11 am-2 am, Sunday 11 am-midnight / 3330 SE Belmont St\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? Both\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? No\\nMore Details: 2 slices person. 14\\" Whole Pies available to order on our website or by phone (phone lines may be busy)"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Buttnut Strut\\n\\nWhat's On It: The base is a spiced sage butternut squash sauce, coated with a nutritional yeast layer, topped with zucchini, lemon pepper cauliflower, and a three mushroom blend. \\n\\nWhat They Say About It: Pizza has endless possibilities, but most people choose the basics. One goal Mississippi Pizza has is to make cheeseless/meatless pizzas shine. Pizza isn't just meat and cheese. It's a delicate balance of the right flavor combinations. In life we need that balance as well. Pizza can fit that vibe, so healthy and delicious, it will make you Strut. \\n\\nWhere and When to Get It: Mississippi Pizza Pub and Atlantis Lounge, Monday-Thursday 11 am-11 pm, Friday-Saturday 11 am-12 am, Sunday 11 am-11 pm  / 3552 N Mississippi Ave\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegan\\nBy the Slice or Whole Pie? By the Slice, Whole Pie\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? Yes4 Slice per customer, and 2 whole max per customer\\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Sweet Hickory\\n\\nWhat's On It: Honey hickory BBQ beef, Mama Lil's Hungarian sweet peppers, house-pickled red onions and Wisconsin brick cheese with a caramelized edge.\\n\\nWhat They Say About It: We wanted to avoid using pork to have broader appeal and thought seasoned beef would be a fun alternative. It's very flavorful so we wanted strong flavors in the veggies to match, otherwise they'd just get lost. Our kitchen crew loves everything pickled so the choice was easy.\\n\\nWhere and When to Get It: Assembly Brewing, 11 am-10 pm daily / 6112 SE Foster Rd\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Whole Pie\\nAllow Minors? No\\nAllow Takeout? No\\nAllow Delivery? No\\nPurchase Limit per Customer? I Need To Explain\\nDaily Availability Limit? Yes100\\nMore Details: 2 pies "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Pepper Ann\\n\\nWhat's On It: San Marzano tomato sauce, cashew mozzarella, vegan sausage, pickled red peppers\\n\\nWhat They Say About It: Our Pepper Ann pizza is a blast of 2000s after-school cartoon-watching, pizza-snacking nostalgia, but better! The Pepper Ann is an all-vegan pie hand-tossed and topped with a slew of scratch- and house-made ingredients including our San Marzano tomato sauce, Italian sausage, and cashew mozzarella cheese. \\n\\nWhere and When to Get It: Virtuous Pie, Monday-Thursday 11 am-10 pm, Friday-Sunday 11 am-11 pm / 1126 SE Division St, Suite 200\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegan\\nBy the Slice or Whole Pie? By the Slice\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: 100 x 35\\n\\nWhat's On It: Creole-style sauce (aka salsa criolla), mozzarella, ripe plantains, and spicy cilantro chimichurri\\n\\nWhat They Say About It: Bringing you a slice all the way from the island! Our chef, Neishma Balaguer Sagarida, is a Puerto Rican native and wanted to feature the 100 x 35 (measurements of Puerto Rico) on a pizza. You'll easily be transported to sunshine, sandy beaches, and warm waters after just one bite. Travel north to indulge in our NY-style pizzas, house made pasta, and seasonal cocktails. We can't wait to see you!\\n\\nWhere and When to Get It: Fino Bistro & Pizzeria, Monday-Thursday 11:30 am-9 pm, Friday-Saturday 11:30 am-10 pm, Sunday 11:30 am-9 pm / 8225 N Denver Ave\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? By the Slice\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? I Need To Explain\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? No\\nMore Details: Only allowed 2 slices per person. We offer DoorDash for delivery but slices ARE NOT available via delivery. "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Moroccan Lemon\\n\\nWhat's On It: Preserved lemons, ricotta, hot honey\\n\\nWhat They Say About It: Delicious vegetarian!  Refreshing lemon and smooth ricotta with a touch of spice!\\n\\nWhere and When to Get It: Via Chicago, Monday 12-8 pm, Tuesday-Thursday 12-9 pm, Friday-Saturday 12-10 pm, Sunday 12-8 pm / 2013 NE Alberta\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? By the Slice\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? Yesno\\nMore Details: Two slices per person allowed.  And one whole pizza"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Crème de la crème\\n\\nWhat's On It: A mushroom duxelles with house-made Italian sausage, roast garlic cream sauce, and French feta cheese\\n\\nWhat They Say About It: The mushrooms and French feta cheese really shine bright in this non-traditional pizza. The Garlic cream sauce with Italian sausage give the Crème de la crème a rich and filling element that you will remember. \\n\\nWhere and When to Get It: Carina Lounge, Wednesday-Thursday 4:30-9 pm, Friday-Saturday 4:30-10 pm, Sunday 4:30-8 pm / 410 NW 21st Ave\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? Whole Pie\\nAllow Minors? Yes\\nAllow Takeout? No\\nAllow Delivery? No\\nPurchase Limit per Customer? No\\nDaily Availability Limit? No\\nMore Details: "}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Reservoir Hogs\\n\\nWhat's On It: Smoked pork, savory garlic and olive oil base, pickles, and red onion, with a drizzle of both mustard and our own zesty Carolina BBQ sauce.\\n\\nWhat They Say About It: House-smoked meats by Biggz himself are BACK at Division this year! He'll be slow-smoking pork for days to pair perfectly with our new Zesty Carolina BBQ sauce—made special for Pizza Week 2023! Come get yer mitts on a slice or three! \\n\\nWhere and When to Get It: Atlas Pizza, 3570 SE Division St / 4-10 pm daily\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Meat\\nBy the Slice or Whole Pie? By the Slice\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? No\\nMore Details: 3 Pizza Week slices per customer per day!"}`,
  },
  {
    data: `{"1":2,"2":"What It's Called: Mapo Tofu Pizza\\n\\nWhat's On It: Fried Ota tofu (made fresh right across the street!) marinated in a blend of spices, roasted squash, bell peppers, red onion, green onion, and mozzarella, on a marinara sauce base. \\n\\nWhat They Say About It: We have been wanting to make this pizza for a bit. Danwei participates in Pizza Week every year and we dig the challenge. We tested this last year and it was a hit! \\n\\nWhere and When to Get It: Danwei Canting, 12-9 pm daily / 803 SE Stark Street\\n\\nThe Fine Print!\\n\\nMeat or Vegetarian? Vegetarian\\nBy the Slice or Whole Pie? By the Slice\\nAllow Minors? Yes\\nAllow Takeout? Yes\\nAllow Delivery? No\\nPurchase Limit per Customer? Yes\\nDaily Availability Limit? Yes2 slices per person\\nMore Details: 2 slices per person"}`,
  },
];

export default pizzaData;
